### ISSUE TITLE
Linux系统适配

### ISSUE THREAD

**Issue by zs6e** [SchneeHertz/exhentai-manga-manager#169]
请问您曾经试过在linux系统下build过这个项目吗？我在Ubuntu下用npm试了一下，但是执行的时只显示一个空白的窗口，提示electron: Failed to load URL: file:///home/xxxx/exhentai-manga-manager/out/linux-unpacked/resources/app.asar/dist/index.html with error: ERR_FILE_NOT_FOUND。

**Comment by SchneeHertz** [comment]
> 请问您曾经试过在linux系统下build过这个项目吗？我在Ubuntu下用npm试了一下，但是执行的时只显示一个空白的窗口，提示electron: Failed to load URL: file:///home/xxxx/exhentai-manga-manager/out/linux-unpacked/resources/app.asar/dist/index.html with error: ERR_FILE_NOT_FOUND。

没有，我一直使用的windows
你可能需要调整package.json中electron-builder的设置
以及
修改调用7z的代码
https://github.com/SchneeHertz/exhentai-manga-manager/blob/5d385e690a816076cc7965bfe9480f1fdc8452ca/fileLoader/archive.js#L10

**Comment by SchneeHertz** [comment]
如果你没有使用package.json中的script，在build electron的包之前，应该先执行vite build打包前端代码

**Comment by bennyz327** [comment]
剛好在用 Archlinux 試著包了一下。模塊 sharp 會報錯

我先在 `package.json`  build 屬性增加
```
"linux": {
  "target": [
    "AppImage"
  ]
}
``` 
然後
```
npm ci
npm dist
./out/exhentai-manga-manager-1.6.1.AppImage
```

錯誤訊息
```
./out/exhentai-manga-manager-1.6.1.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Could not load the "sharp" module using the linux-x64 runtime
ERR_DLOPEN_FAILED: libvips-cpp.so.42: ç¡æ³éåå±ç¨ç©ä»¶: æ²ææ­¤ä¸æªæ¡æç®é
Possible solutions:
- Please upgrade Node.js:
    Found 18.16.1
    Requires ^18.17.0 || ^20.3.0 || >=21.0.0
- Consult the installation documentation:
    See https://sharp.pixelplumbing.com/install
    at Object.<anonymous> (/tmp/.mount_exhentH96u2Y/resources/app.asar/node_modules/sharp/lib/sharp.js:113:9)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at node:internal/modules/cjs/loader:967:12
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_exhentH96u2Y/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
```

不知道如何修，跟包管理器有關嗎？

**Comment by SchneeHertz** [comment]
> 剛好在用 Archlinux 試著包了一下。模塊 sharp 會報錯
> 
> 我先在 `package.json` build 屬性增加
> 
> ```
> "linux": {
>   "target": [
>     "AppImage"
>   ]
> }
> ```
> 
> 然後
> 
> ```
> npm ci
> npm dist
> ./out/exhentai-manga-manager-1.6.1.AppImage
> ```
> 
> 錯誤訊息
> 
> ```
> ./out/exhentai-manga-manager-1.6.1.AppImage
> A JavaScript error occurred in the main process
> Uncaught Exception:
> Error: Could not load the "sharp" module using the linux-x64 runtime
> ERR_DLOPEN_FAILED: libvips-cpp.so.42: ç¡æ³éåå±ç¨ç©ä»¶: æ²ææ­¤ä¸æªæ¡æç®é
> Possible solutions:
> - Please upgrade Node.js:
>     Found 18.16.1
>     Requires ^18.17.0 || ^20.3.0 || >=21.0.0
> - Consult the installation documentation:
>     See https://sharp.pixelplumbing.com/install
>     at Object.<anonymous> (/tmp/.mount_exhentH96u2Y/resources/app.asar/node_modules/sharp/lib/sharp.js:113:9)
>     at Module._compile (node:internal/modules/cjs/loader:1271:14)
>     at Object..js (node:internal/modules/cjs/loader:1326:10)
>     at Module.load (node:internal/modules/cjs/loader:1126:32)
>     at node:internal/modules/cjs/loader:967:12
>     at Function._load (node:electron/js2c/asar_bundle:2:13327)
>     at Module.require (node:internal/modules/cjs/loader:1150:19)
>     at require (node:internal/modules/cjs/helpers:110:18)
>     at Object.<anonymous> (/tmp/.mount_exhentH96u2Y/resources/app.asar/node_modules/sharp/lib/constructor.js:10:1)
>     at Module._compile (node:internal/modules/cjs/loader:1271:14)
> ```
> 
> 不知道如何修，跟包管理器有關嗎？ (我用的是 Node.js v20.17.0 )

node版本低了，升到20或者22再试试

**Comment by bennyz327** [comment]
刪掉 dist node_modules out 資料夾後升到 22.8.0 重新執行了一次
```
~/source/exhentai-manga-manager git:[master]
nvm use 22
Now using node v22.8.0 (npm v10.8.2)
```
```
~/source/exhentai-manga-manager git:[master]
npm ci
npm warn deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated

added 603 packages, and audited 604 packages in 23s

90 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
```
~/source/exhentai-manga-manager git:[master]
npm run dist

> exhentai-manga-manager@1.6.1 dist
> auto-changelog && vite build && electron-builder

(node:175958) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
auto-changelog: 34 kB written to CHANGELOG.md
vite v2.9.18 building for production...
✓ 24701 modules transformed.
dist/index.html                  0.43 KiB
dist/assets/index.c14acc06.css   344.06 KiB / gzip: 48.48 KiB
dist/assets/index.95e4e339.js    1659.93 KiB / gzip: 542.38 KiB

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
  • electron-builder  version=24.13.3 os=6.10.7-arch1-1
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=out/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sqlite3@5.1.6 platform=linux arch=x64
  • packaging       platform=linux arch=x64 electron=26.6.1 appOutDir=out/linux-unpacked
  • building        target=AppImage arch=x64 file=out/exhentai-manga-manager-1.6.1.AppImage
  • default Electron icon is used  reason=application icon is not set
```
執行報錯不一樣了XD，但還是 sharp
```
~/source/exhentai-manga-manager git:[master]
./out/exhentai-manga-manager-1.6.1.AppImage
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'sharp'
Require stack:
- /tmp/.mount_exhentfXcsG4/resources/app.asar/index.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:117576)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/tmp/.mount_exhentfXcsG4/resources/app.asar/index.js:8:15)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Object..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
```

**Comment by SchneeHertz** [comment]
```
PS D:\GitHub\exhentai-manga-manager> npm run dist

> exhentai-manga-manager@1.6.1 dist
> auto-changelog && vite build && electron-builder

(node:10464) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
auto-changelog: 34 kB written to CHANGELOG.md
vite v2.9.18 building for production...
✓ 24702 modules transformed.
dist/index.html                  0.45 KiB
dist/assets/index.99f887f5.css   344.06 KiB / gzip: 48.48 KiB
dist/assets/index.461e5ca1.js    1660.80 KiB / gzip: 542.79 KiB

(!) Some chunks are larger than 500 KiB after minification. Consider:
- Using dynamic import() to code-split the application
- Use build.rollupOptions.output.manualChunks to improve chunking: https://rollupjs.org/guide/en/#outputmanualchunks
- Adjust chunk size limit for this warning via build.chunkSizeWarningLimit.
  • electron-builder  version=24.13.3 os=10.0.19045
  • loaded configuration  file=package.json ("build" field)
  • writing effective config  file=out\builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=sharp@0.32.6, sqlite3@5.1.6 platform=win32 arch=x64
  • install prebuilt binary  name=sharp version=0.32.6 platform=win32 arch=x64 napi=
• packaging       platform=win32 arch=x64 electron=26.6.1 appOutDir=out\win-unpacked
  • building        target=zip arch=x64 file=out\exhentai-manga-manager-1.6.1-win.zip
  • building        target=nsis file=out\exhentai-manga-manager Setup 1.6.1.exe archs=x64 oneClick=false perMachine=false
  • building block map  blockMapFile=out\exhentai-manga-manager Setup 1.6.1.exe.blockmap
  ```
  这是windows打包的输出，像是sharp没有被打包进去

**Comment by SchneeHertz** [comment]
sharp的issue有提到过类似的问题，不知道是不是这个原因，升级sharp的版本到0.33.0可能可以解决
https://github.com/lovell/sharp/issues/2764

**Comment by zs6e** [comment]
又测试了一下发现是我的问题....我的manga目录下不规范的文件太多，Linux下运行好像是没啥问题了，下面就剩改一下这个const _7z = path.join(getRootPath(), 'resources/extraResources/7z.exe' 了

**Comment by SchneeHertz** [comment]
> import { gh_token } from '../../secret_key.json'

这是导入github的token用于检查更新，注释掉也行，就是检查更新时会出错而已

**Comment by SchneeHertz** [comment]
> 又测试了一下发现是我的问题....我的manga目录下不规范的文件太多 Linux下运行好像是没啥问题了，下面就剩改一下这个const _7z = path.join(getRootPath(), 'resources/extraResources/7z.exe' 了
> 
> 顺便问一下，load漫画的时候提示Segmentation fault是什么意思呀，扫描漫画导致程序退出的时候控制台就会显示这个

没遇到过这个错误，可能是7z不能正常用导致的吧

Linux把这一行改成 const _7z = '7z'
在软件包管理中装上p7zip应该就可以用了吧，大概

**Comment by zs6e** [comment]
试了一下，需要填写完整路径，比如const _7z = '/usr/lib/p7zip/7z'。或者干脆把p7zip下面的文件拷贝到extraResources目录下。

现在在ubuntu下运行的挺好的，就是偶尔会遇到 MEMORY-ERROR : exhantai-manga-manager[19645]: GSlice: assertion failed: sinfo ->n_allocated > 0
