### ISSUE TITLE
无法获得exhentai上的元数据

### ISSUE THREAD

**Issue by xingzhi1234** [SchneeHertz/exhentai-manga-manager#8]
![image](https://user-images.githubusercontent.com/41225752/174230179-73e94866-a477-4afc-bef2-b6e2f3aafbb0.png)
能获取元数据的本子，尝试获取ex元数据会出现这个报错，带lolicon标签的，尝试获取元数据直接get tag failed了。
我是通过vpn浏览的exhentai，账号是可以正常登上ex的，设置里cookie填的也是对的。代理服务器没填

**Comment by xingzhi1234** [comment]
![image](https://user-images.githubusercontent.com/41225752/174231317-8d9ce5a5-8939-4aa8-934e-9af6efcacb3f.png)
获取评论会出现这个报错

**Comment by xingzhi1234** [comment]
连vpn可以获取ehentai上的元数据，但获取不了exhentai的

**Comment by SchneeHertz** [comment]
@xingzhi1234 看来还是网络的问题，你换个VPN或者其他的代理软件试试吧

**Comment by xingzhi1234** [comment]
> @xingzhi1234 看来还是网络的问题，你换个VPN或者其他的代理软件试试吧

应该不是，连vpn是可以正常访问里站的，但里站元数据就是获取不了（
连vpn不用填设置里的代理吧

**Comment by xingzhi1234** [comment]
尝试获取里站限定的本子的元数据并不是等很久然后报超时，而是很快显示get tag falied，会不会是请求被e站拦下了
可我的号已经有里站权限了啊

**Comment by xingzhi1234** [comment]
cookie填的是绝对没错的，vpn也没问题可以访问里站，表站元数据可以正常获取，但是里站元数据无法获取。
这是错误信息
![image](https://user-images.githubusercontent.com/41225752/174288773-c8a3f9f5-01a7-48b3-9553-f0ced788b8d8.png)

**Comment by xingzhi1234** [comment]
错误报告是这个：Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at index.70f7edb6.js:54:17823

**Comment by xingzhi1234** [comment]
手动输入网址获取里站元数据是没问题的（

**Comment by xingzhi1234** [comment]
GET https://e-hentai.org/?f_shash=96CA9D14779A68690A196F992B0AB48FE2FADE8E&fs_similar=1&fs_exp=on net::ERR_PROXY_CONNECTION_FAILED
index.70f7edb6.js:42 Uncaught (in promise) Error: Network Error
    at oS (index.70f7edb6.js:42:204668)
    at XMLHttpRequest.d.onerror (index.70f7edb6.js:43:2169)

**Comment by SchneeHertz** [comment]
你再看下代理服务器的设置
如果你用的是clash，默认应该填 http://127.0.0.1:7890/
v2rayN是 http://127.0.0.1:1081/
如果是socks类型的代理，填 socks://127.0.0.1:端口
VPN类的代理我没测试过，如果是全局的，应该是代理服务器里什么都不填，有iptables的建议自己配置下(我不会
建议附上设置里代理服务器部分的截图(不要截到exhentai cookie的部分)，和使用的代理软件的截图，只看错误信息很难判断

**Comment by tokyoyami** [comment]
我今天也碰到这个问题了，在去年年底我是用过老版本的软件没有碰到问题，今天用新版本进去也是获取tag失败和同样的网址报错链接get ex page failed because Error: connect ETIMEDOUT 173.252.105.21:443，而在漫画详情页面输入具体网址匹配tag也能成功。我使用的是clash for windos的全局，是可以正常登录其他所有e系软件和网址的，就感觉很奇怪是不是有什么bug

**Comment by SchneeHertz** [comment]
> 我今天也碰到这个问题了，在去年年底我是用过老版本的软件没有碰到问题，今天用新版本进去也是获取tag失败和同样的网址报错链接get ex page failed because Error: connect ETIMEDOUT 173.252.105.21:443，而在漫画详情页面输入具体网址匹配tag也能成功。我使用的是clash for windos的全局，是可以正常登录其他所有e系软件和网址的，就感觉很奇怪是不是有什么bug

请参考代理服务器的设置，或者提供设置的截图供判断
